language: python
pre_install:
  - openssl aes-256-cbc -K $encrypted_fed0fe4f29f8_key -iv $encrypted_fed0fe4f29f8_iv -in deploy.key.enc -out deploy.key -d
install:
  - pip2 install hyde
script:
  - hyge gen
after_success:
  - hyde publish -p github
  - .travis/push.sh
