language: python
before_install:
  - openssl aes-256-cbc -K $encrypted_fed0fe4f29f8_key -iv $encrypted_fed0fe4f29f8_iv -in deploy.key.enc -out ~/.ssh/id_rsa -d
  - git clone git@github.com:CoinNation/coinnation.github.io.git
install:
  - pip2 install hyde
script:
  - hyde gen -r
after_success:
  - hyde publish -p github
#  - .travis/push.sh
